;; cl-pinner - A project template generated by ahungry-fleece
;; Copyright (C) 2016 Your Name <cl-pinner@example.com>
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;;; cl-pinner.lib.stub.lisp

(in-package #:cl-user)

(defpackage cl-pinner.lib.fetch
  (:use :cl)
  (:export
   :echo))

(in-package #:cl-pinner.lib.stub)

(defparameter *base-directory* (asdf:system-source-directory :cl-pinner))

(defun fetch-git (package uri version)
  "Clone and check out from URI the specified VERSION."
  (let ((clone-to-directory (format nil "pinned/~a-~a" package version))
        (path (merge-pathnames clone-to-directory *base-directory*))
        (cwd (sb-posix:getcwd)))
    (sb-ext:run-program "git" '("clone" uri path))
    (sb-posix:chdir path)
    (sb-ext:run-program "git" '("checkout" version))
    (sb-posix:chdir cwd)))

(defun echo (input)
  input)

;;; "cl-pinner.lib.stub" goes here. Hacks and glory await!
